package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * Amigos generated by hbm2java
 */
public class Amigos implements java.io.Serializable {

	private AmigosId id;

	public Amigos() {
	}

	public Amigos(AmigosId id) {
		this.id = id;
	}

	public AmigosId getId() {
		return this.id;
	}

	public void setId(AmigosId id) {
		this.id = id;
	}

}
