package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * Calendarios generated by hbm2java
 */
public class Calendarios implements java.io.Serializable {

	private CalendariosId id;

	public Calendarios() {
	}

	public Calendarios(CalendariosId id) {
		this.id = id;
	}

	public CalendariosId getId() {
		return this.id;
	}

	public void setId(CalendariosId id) {
		this.id = id;
	}

}
