package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * Musica generated by hbm2java
 */
public class Musica implements java.io.Serializable {

	private MusicaId id;
	private String genero;
	private int recomendado;
	private int puntuacion;
	private String tipo;
	private String cantante;

	public Musica() {
	}

	public Musica(MusicaId id, String genero, int recomendado, int puntuacion, String tipo,String cantante) {
		this.id = id;
		this.genero = genero;
		this.recomendado = recomendado;
		this.puntuacion = puntuacion;
		this.tipo = tipo;
		this.cantante = cantante;
	}

	public MusicaId getId() {
		return this.id;
	}

	public void setId(MusicaId id) {
		this.id = id;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public int getRecomendado() {
		return this.recomendado;
	}

	public void setRecomendado(int recomendado) {
		this.recomendado = recomendado;
	}

	public int getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(int puntuacion) {
		this.puntuacion = puntuacion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCantante() {
		return cantante;
	}

	public void setCantante(String cantante) {
		this.cantante = cantante;
	}
	

}
