package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas implements java.io.Serializable {

	private PeliculasId id;
	private String genero;
	private int recomendado;
	private int puntuacion;
	private String director;

	public Peliculas() {
	}

	public Peliculas(PeliculasId id, String genero, int recomendado, int puntuacion,String director) {
		this.id = id;
		this.genero = genero;
		this.recomendado = recomendado;
		this.puntuacion = puntuacion;
		this.director = director;
	}

	public PeliculasId getId() {
		return this.id;
	}

	public void setId(PeliculasId id) {
		this.id = id;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public int getRecomendado() {
		return this.recomendado;
	}

	public void setRecomendado(int recomendado) {
		this.recomendado = recomendado;
	}

	public int getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(int puntuacion) {
		this.puntuacion = puntuacion;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}
	

}
