package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * PeliculasId generated by hbm2java
 */
public class PeliculasId implements java.io.Serializable {

	private String propietario;
	private String nombre;
	private String director;

	public PeliculasId() {
	}

	public PeliculasId(String propietario, String nombre, String director) {
		this.propietario = propietario;
		this.nombre = nombre;
		this.director = director;
	}

	public String getPropietario() {
		return this.propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PeliculasId))
			return false;
		PeliculasId castOther = (PeliculasId) other;

		return ((this.getPropietario() == castOther.getPropietario()) || (this.getPropietario() != null
				&& castOther.getPropietario() != null && this.getPropietario().equals(castOther.getPropietario())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getDirector() == castOther.getDirector()) || (this.getDirector() != null
						&& castOther.getDirector() != null && this.getDirector().equals(castOther.getDirector())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPropietario() == null ? 0 : this.getPropietario().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getDirector() == null ? 0 : this.getDirector().hashCode());
		return result;
	}

}
