package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * Series generated by hbm2java
 */
public class Series implements java.io.Serializable {

	private SeriesId id;
	private String genero;
	private int recomendado;
	private int puntuacion;
	private int temporadas;

	public Series() {
	}

	public Series(SeriesId id, String genero, int recomendado, int puntuacion, int temporadas) {
		this.id = id;
		this.genero = genero;
		this.recomendado = recomendado;
		this.puntuacion = puntuacion;
		this.temporadas = temporadas;
	}

	public SeriesId getId() {
		return this.id;
	}

	public void setId(SeriesId id) {
		this.id = id;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public int getRecomendado() {
		return this.recomendado;
	}

	public void setRecomendado(int recomendado) {
		this.recomendado = recomendado;
	}

	public int getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(int puntuacion) {
		this.puntuacion = puntuacion;
	}

	public int getTemporadas() {
		return this.temporadas;
	}

	public void setTemporadas(int temporadas) {
		this.temporadas = temporadas;
	}

}
