package clasesHibernate;
// Generated 09-feb-2018 19:50:59 by Hibernate Tools 5.2.8.Final

/**
 * SeriesId generated by hbm2java
 */
public class SeriesId implements java.io.Serializable {

	private String propietario;
	private String nombre;

	public SeriesId() {
	}

	public SeriesId(String propietario, String nombre) {
		this.propietario = propietario;
		this.nombre = nombre;
	}

	public String getPropietario() {
		return this.propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeriesId))
			return false;
		SeriesId castOther = (SeriesId) other;

		return ((this.getPropietario() == castOther.getPropietario()) || (this.getPropietario() != null
				&& castOther.getPropietario() != null && this.getPropietario().equals(castOther.getPropietario())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPropietario() == null ? 0 : this.getPropietario().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
